name: Deploy Go App with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Логинимся в DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Собираем и пушим Docker-образ
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # 4. Деплой на сервер
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
            sudo docker pull $IMAGE_NAME:latest
            sudo docker stop satellite-app || true
            sudo docker rm satellite-app || true
            sudo docker run -d --name satellite-app -p 8080:8080 $IMAGE_NAME:latest
