name: Deploy Go App with Docker

on:
  push:
    branches:
      - main

jobs:
  # 1. Линтер
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: ./cmd/... ./internal/... ./pkg/...

  # 2. Билд и пуш Docker-образа (только если линтер успешен)
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  # 3. Деплой на сервер (только если билд успешен)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
            sudo docker pull $IMAGE_NAME:latest
            sudo docker stop satellite-app || true
            sudo docker rm satellite-app || true
            sudo docker run -d --name satellite-app -p 8080:8080 $IMAGE_NAME:latest
