name: Deploy Go App with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Ставим Go и линтер
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.59.1

      # 3. Запускаем линтер
      - name: Run linter
        run: golangci-lint run ./...

      # 4. Логинимся в DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Собираем и пушим Docker-образ
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # 6. Деплой на сервер
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/satellite-app
            sudo docker pull $IMAGE_NAME:latest
            sudo docker stop satellite-app || true
            sudo docker rm satellite-app || true
            sudo docker run -d --name satellite-app -p 8080:8080 $IMAGE_NAME:latest
